name: Build Fedora

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '13 4 * * *'

permissions:
  contents: read
  packages: write

env:
  REPO_URL: quay.io/osbuild/fedora-bootc
  CACHE_URL: ghcr.io/${{ github.repository }}/cache

jobs:
  fedora-build:
    name: fedora-${{ matrix.tag }}-${{ matrix.arch }}
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - containerfile: Containerfile.f43-qcow2
            tag: 43-qcow2
            arch: x86_64
          - containerfile: Containerfile.f43-qcow2
            tag: 43-qcow2
            arch: aarch64
          - containerfile: Containerfile.f43-gce
            tag: 43-gce
            arch: x86_64
          - containerfile: Containerfile.f43-gce
            tag: 43-gce
            arch: aarch64
          - containerfile: Containerfile.f43-azure
            tag: 43-azure
            arch: x86_64
          - containerfile: Containerfile.f43-azure
            tag: 43-azure
            arch: aarch64
          - containerfile: Containerfile.f43-ec2
            tag: 43-ec2
            arch: x86_64
          - containerfile: Containerfile.f43-ec2
            tag: 43-ec2
            arch: aarch64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to registries
        uses: ./.github/actions/login-registry
        with:
          username: ${{ secrets.REPO_USERNAME }}
          password: ${{ secrets.REPO_PASSWORD }}
          cache_username: ${{ github.actor }}
          cache_password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: ./.github/actions/build-push
        with:
          repo_url: ${{ env.REPO_URL }}
          cache_url: ${{ env.CACHE_URL }}
          tag: ${{ matrix.tag }}
          arch: ${{ matrix.arch }}
          containerfile: ${{ matrix.containerfile }}

  fedora-manifest:
    name: fedora-manifest
    runs-on: ubuntu-latest
    needs: fedora-build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download matrix info
        uses: actions/download-artifact@v4
        with:
          pattern: matrix-*
          path: matrix-artifacts
          merge-multiple: false

      - name: Login to registries
        uses: ./.github/actions/login-registry
        with:
          username: ${{ secrets.REPO_USERNAME }}
          password: ${{ secrets.REPO_PASSWORD }}
          cache_username: ${{ github.actor }}
          cache_password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create multi-arch manifests
        uses: ./.github/actions/create-manifest
        with:
          repo_url: ${{ env.REPO_URL }}
          cache_url: ${{ env.CACHE_URL }}
          matrix_artifacts_path: matrix-artifacts
